Update patch set 3
Patch Set 3:

This fixes one part of the problem but still fails with a different error

ERROR: /home/paladox/gerrit/plugins/cloud-notifications/BUILD:19:1: Java compilation in rule '//plugins/cloud-notifications:cloud-notifications__plugin' failed: Worker process sent response with exit code: 1.
plugins/cloud-notifications/src/main/java/com/ruesga/gerrit/plugins/fcm/handlers/EventHandler.java:194: error: cannot find symbol
    private boolean add(Set<Integer> watchers, AccountProjectWatch w,
                                               ^
  symbol:   class AccountProjectWatch
  location: class EventHandlerplugins/cloud-notifications/src/main/java/com/ruesga/gerrit/plugins/fcm/handlers/ChangeAbandonedEventHandler.java:20: error: package com.google.gerrit.reviewdb.client.AccountProjectWatch does not exist
import com.google.gerrit.reviewdb.client.AccountProjectWatch.NotifyType;
                                                            ^plugins/cloud-notifications/src/main/java/com/ruesga/gerrit/plugins/fcm/handlers/EventHandler.java:179: error: cannot find symbol
            for (AccountProjectWatch w : reviewdb.get().accountProjectWatches()
                                                       ^
  symbol:   method accountProjectWatches()
  location: interface ReviewDbplugins/cloud-notifications/src/main/java/com/ruesga/gerrit/plugins/fcm/handlers/EventHandler.java:179: error: cannot find symbol
            for (AccountProjectWatch w : reviewdb.get().accountProjectWatches()
                 ^
  symbol:   class AccountProjectWatch
  location: class EventHandlerplugins/cloud-notifications/src/main/java/com/ruesga/gerrit/plugins/fcm/handlers/EventHandler.java:183: error: cannot find symbol
            for (AccountProjectWatch w : reviewdb.get().accountProjectWatches()
                                                       ^
  symbol:   method accountProjectWatches()
  location: interface ReviewDbplugins/cloud-notifications/src/main/java/com/ruesga/gerrit/plugins/fcm/handlers/EventHandler.java:183: error: cannot find symbol
            for (AccountProjectWatch w : reviewdb.get().accountProjectWatches()
                 ^
  symbol:   class AccountProjectWatch
Target //plugins/cloud-notifications:cloud-notifications failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.221s, Critical Path: 3.10s

which i doint know how to fix.

Was caused by https://github.com/gerrit-review/gerrit/commit/b043d448a7f9d8f00a9279a698c3de357002c596

Patch-set: 3
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>